#!/usr/bin/python3.10

import argparse 
import sys

parser = argparse.ArgumentParser(
    prog="FileReader",
    description="Reads a file, similar to the cat command in native Linux",
    epilog="Written in Python"
)
parser.add_argument("filename",help="The path or name of the file to read.")
parser.add_argument("--lines","-l",help="The number of lines to read.",type=int)
parser.add_argument("--version","-v",action="version",version="1.0.0")

args = parser.parse_args()

try:
    f = open(args.filename,"r")
    limit = args.lines
except Exception:
    print(f"Error: File not found or unable to open file.")
    sys.exit(1)
else:
    lines = f.readlines()
    if limit:
        lines = lines[0:limit] # [0:2] | indexing
    for line in lines:
        print(line.strip())
    f.close()